language: node_js
node_js: 
  - "9"
  
script: echo "npm test temporarily disabled"

deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    
notifications:
  email:
    recipients:
    - type@codename.co
    - arnaud@codename.co
    on_success: change
    on_failure: always

branches:
  only:
  - master
